#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication surfaceFeatures

runApplication blockMesh

# Uwaga  !! Pominięto toposety: 2 i 4.

for i in 1 3 5 6
do
    runApplication -a foamDictionary system/refineMeshDict -entry set -set c${i}

    runApplication -a topoSet

    runApplication -a refineMesh -dict refineMeshDict -overwrite
done

    runApplication -a foamDictionary system/refineMeshDict.e1e2e3 -entry set -set c7
    runApplication -a topoSet
    runApplication -a refineMesh -dict refineMeshDict.e1e2e3 -overwrite

    runApplication -a foamDictionary system/refineMeshDict.e1e2e3 -entry set -set c8
    runApplication -a topoSet
    runApplication -a refineMesh -dict refineMeshDict.e1e2e3 -overwrite

#runApplication snappyHexMesh -overwrite

#runApplication renumberMesh -noFields -overwrite

#------------------------------------------------------------------------------
