#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication surfaceFeatures

runApplication blockMesh -dict system/blockMeshDict

for i in 1 2 3 4 5 6
do
    runApplication -a foamDictionary system/refineMeshDict -entry set -set c${i}
    runApplication -a topoSet -dict system/topoSetDict
    runApplication -a refineMesh -dict system/refineMeshDict -overwrite
done


runApplication snappyHexMesh -dict system/snappyHexMeshDict -overwrite

runApplication renumberMesh -noFields -overwrite

#------------------------------------------------------------------------------
